---
version: "3"
services:
  download-data:
    image: freqtradeorg/freqtrade:stable
    container_name: download-data
    volumes:
      - ".:/freqtrade/user_data/data"
    command: >
      download-data
      --timerange ${START_DATE:-20240101}-${END_DATE:-20250101}
      --timeframe ${TIMEFRAMES:-5m 15m 1h 4h 1d}
      --datadir user_data/data/${EXCHANGE:-binance}
      --config user_data/data/trading_mode-${TRADINGMODE:-futures}.json
      --config user_data/data/download-data-${EXCHANGE:-binance}-${TRADINGMODE:-futures}-usdt.json
      --config user_data/data/download-data-${EXCHANGE:-binance}-blacklist.json
